version: "3.8"

services:
  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: ubuntu-desktop-vnc
    privileged: true
    ports:
      - "6081:80"
    environment:
      - HTTP_PASSWORD=mypassword
    volumes:
      - /workspaces/fastapi_django_main_lives:/code
      - /dev/shm:/dev/shm
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
