"""
Article Model
============

Generated by Artisan on 2025-06-13 16:49:45
"""

from sqlalchemy import Column, Integer, String, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from typing import Optional

Base = declarative_base()

class Article(Base):
    """
    Article Model
    
    SQLAlchemy model for article table
    """
    
    __tablename__ = "articles"
    
    # Primary Key
    id = Column(Integer, primary_key=True, index=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Add your fields here
    # name = Column(String(255), nullable=False)
    # email = Column(String(255), unique=True, index=True)
    # is_active = Column(Boolean, default=True)
    
    def __repr__(self):
        return f"<Article(id={self.id})>"
    
    def to_dict(self):
        """Convert model to dictionary"""
        return {
            "id": self.id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            # Add your fields here
        }
